version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name aws-work04 --s3-location s3://work03-s/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src